// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProfile(arg1) {
  return window['go']['main']['App']['ApplyProfile'](arg1);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DetectNvm() {
  return window['go']['main']['App']['DetectNvm']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetHostsEntries() {
  return window['go']['main']['App']['GetHostsEntries']();
}

export function GetNvmDir() {
  return window['go']['main']['App']['GetNvmDir']();
}

export function GetNvmRoot() {
  return window['go']['main']['App']['GetNvmRoot']();
}

export function GetNvmVersion() {
  return window['go']['main']['App']['GetNvmVersion']();
}

export function GetSystemLanguage() {
  return window['go']['main']['App']['GetSystemLanguage']();
}

export function GetUserLanguagePreference() {
  return window['go']['main']['App']['GetUserLanguagePreference']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InstallNodeVersion(arg1) {
  return window['go']['main']['App']['InstallNodeVersion'](arg1);
}

export function InstallNvm() {
  return window['go']['main']['App']['InstallNvm']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListNodeVersions() {
  return window['go']['main']['App']['ListNodeVersions']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadProfile(arg1) {
  return window['go']['main']['App']['LoadProfile'](arg1);
}

export function OpenAppDir() {
  return window['go']['main']['App']['OpenAppDir']();
}

export function OpenNodeAvailableList() {
  return window['go']['main']['App']['OpenNodeAvailableList']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function SaveHostsEntries(arg1) {
  return window['go']['main']['App']['SaveHostsEntries'](arg1);
}

export function SaveHostsEntriesWithReadOnlyRestore(arg1) {
  return window['go']['main']['App']['SaveHostsEntriesWithReadOnlyRestore'](arg1);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetNvmDir(arg1) {
  return window['go']['main']['App']['SetNvmDir'](arg1);
}

export function SetUserLanguagePreference(arg1) {
  return window['go']['main']['App']['SetUserLanguagePreference'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SwapIPs(arg1, arg2) {
  return window['go']['main']['App']['SwapIPs'](arg1, arg2);
}

export function ToggleWindowVisibility() {
  return window['go']['main']['App']['ToggleWindowVisibility']();
}

export function UninstallNodeVersion(arg1) {
  return window['go']['main']['App']['UninstallNodeVersion'](arg1);
}

export function UseNodeVersion(arg1) {
  return window['go']['main']['App']['UseNodeVersion'](arg1);
}

export function ValidateHostEntry(arg1) {
  return window['go']['main']['App']['ValidateHostEntry'](arg1);
}
