// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hosts} from '../models';
import {config} from '../models';
import {nvm} from '../models';

export function ApplyProfile(arg1:string):Promise<void>;

export function CreateBackup():Promise<hosts.BackupInfo>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DetectNvm():Promise<boolean>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetAutoStart():Promise<boolean>;

export function GetHostsEntries():Promise<Array<hosts.HostEntry>>;

export function GetNvmDir():Promise<string>;

export function GetNvmRoot():Promise<string>;

export function GetNvmVersion():Promise<string>;

export function GetSystemLanguage():Promise<string>;

export function GetUserLanguagePreference():Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function InstallNodeVersion(arg1:string):Promise<string>;

export function InstallNvm():Promise<string>;

export function ListBackups():Promise<Array<hosts.BackupInfo>>;

export function ListNodeVersions():Promise<Array<nvm.NodeVersion>>;

export function ListProfiles():Promise<Array<hosts.HostsProfile>>;

export function LoadProfile(arg1:string):Promise<hosts.HostsProfile>;

export function OpenAppDir():Promise<void>;

export function OpenNodeAvailableList():Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function SaveHostsEntries(arg1:Array<hosts.HostEntry>):Promise<void>;

export function SaveHostsEntriesWithReadOnlyRestore(arg1:Array<hosts.HostEntry>):Promise<void>;

export function SaveProfile(arg1:string,arg2:Array<hosts.HostEntry>):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetNvmDir(arg1:string):Promise<void>;

export function SetUserLanguagePreference(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function SwapIPs(arg1:Array<hosts.HostEntry>,arg2:number):Promise<Array<hosts.HostEntry>>;

export function ToggleWindowVisibility():Promise<void>;

export function UninstallNodeVersion(arg1:string):Promise<string>;

export function UseNodeVersion(arg1:string):Promise<string>;

export function ValidateHostEntry(arg1:hosts.HostEntry):Promise<void>;
